image: ekino/ci-golang:1.19-2022.08.31

stages:
  - tests
  - release

.job_tests:
  stage: tests

lint:
  extends: .job_tests
  image: golangci/golangci-lint:v1.52.2-alpine
  script:
    - golangci-lint run

tests:
  extends: .job_tests
  script:
    - go test ./...

.release:
  stage: release
  image:
    name: goreleaser/goreleaser:v1.15.2
    entrypoint: ['']
  variables:
    # Disable shallow cloning so that goreleaser can diff between tags to
    # generate a changelog.
    GIT_DEPTH: 0
  artifacts:
    paths:
      - dist/
    expire_in: 1 month
    expose_as: 'Release'

release-snapshot:
  extends: .release
  script:
    - goreleaser release --snapshot --clean
  rules:
    - if: $CI_COMMIT_BRANCH

release:
  extends: .release
  script:
    - goreleaser release --clean
  rules:
    - if: $CI_COMMIT_TAG
